<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * This file keeps track of upgrades to
 * the paper copy report.
 *
 * Sometimes, changes between versions involve
 * alterations to database structures and other
 * major things that may break installations.
 *
 * The upgrade function in this file will attempt
 * to perform all the necessary actions to upgrade
 * your older installation to the current version.
 *
 * If there's something it cannot do itself, it
 * will tell you what you need to do.
 *
 * The commands in here will all be database-neutral,
 * using the methods of database_manager class
 *
 * Please do not forget to use upgrade_set_timeout()
 * before any action that may take longer time to finish.
 *
 * @package quiz_papercopy
 * @copyright 2012 Binghamton University
 * @author Kyle J. Temkin <ktemkin@binghamton.edu>
 * @license   http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

function xmldb_quiz_papercopy_upgrade($oldversion) {

    // Get a reference to the global database manager, which is used
    // to make database upgrades.
    global $DB;
    $dbman = $DB->get_manager();


    //
    // Replace the legacy, poorly structured name "paper_batches" with
    // the more paradigmatic frankenstyle "quiz_papercopy_batches" name.
    //

    if ($oldversion < 2012082903) {

        // Define table paper_batches to be renamed to quiz_papercopy_batches 
        $table = new xmldb_table('paper_batches');

        // If the table exists, rename it.
        if($dbman->table_exists($table)) {

            // Launch rename table for quiz_papercopy_batches
            $dbman->rename_table($table, 'quiz_papercopy_batches');

        } 
        // ... and if it doesn't, ensure that the resultant table exists.
        else {
            $table = new xmldb_table('quiz_papercopy_batches');

            // If the resultant table does _not_ exist...
            if(!$dbman->table_exists($table)) {

                // ... throw an exception to prevent the defective setup from continuing...
                throw new upgrade_exception('quiz_papercopy', 2012082903, 'Neither paper_batches nor quiz_papercopy_batches exist.');
            } 

        }

        //
        // Add the "prerendered" field, which stores the pathnamehash of any existing, pre-rendered copies.
        // [Code automatically generated by Moodle.]
        // 
        
        // Define field prerendered to be added to paper_batches
        $table = new xmldb_table('quiz_papercopy_batches');
        $field = new xmldb_field('prerendered', XMLDB_TYPE_CHAR, '40', null, null, null, null, 'include_key');

        // Conditionally launch add field prerendered
        if (!$dbman->field_exists($table, $field)) {
            $dbman->add_field($table, $field);
        }

        //
        // Add the "prerendered" field, which stores the pathnamehash of any existing, pre-rendered copies.
        // [Code automatically generated by Moodle.]
        // 

        // Define field prerendered_with_key to be added to paper_batches
        $table = new xmldb_table('quiz_papercopy_batches');
        $field = new xmldb_field('prerendered_with_key', XMLDB_TYPE_CHAR, '40', null, null, null, null, 'prerendered');

        // Conditionally launch add field prerendered_with_key
        if (!$dbman->field_exists($table, $field)) {
            $dbman->add_field($table, $field);
        }

        // papercopy savepoint reached

        //
        // Drop the "delivery_method" field, which is no longer used; as 
        // delivery method is determined automatically at download time.
        //

        // Define field delivery_method to be dropped from paper_batches
        $table = new xmldb_table('quiz_papercopy_batches');
        $field = new xmldb_field('delivery_method');

        // Conditionally launch drop field delivery_method
        if ($dbman->field_exists($table, $field)) {
            $dbman->drop_field($table, $field);
        }

    
        //
        // Drop the "include key" field, which is no longer used; as key inclusion is 
        // specified at download time.
        //

        // Define field include_key to be dropped from paper_batches
        $table = new xmldb_table('quiz_papercopy_batches');
        $field = new xmldb_field('include_key');

        // Conditionally launch drop field include_key
        if ($dbman->field_exists($table, $field)) {
            $dbman->drop_field($table, $field);
        }

        // papercopy savepoint reached
        upgrade_plugin_savepoint(true, 2012082903, 'quiz', 'papercopy');
    }

    // Upgrade to 8-29-12 V4
    if ($oldversion < 2012082904) {

        // Define field prerendered_key_only to be added to quiz_papercopy_batches
        $table = new xmldb_table('quiz_papercopy_batches');
        $field = new xmldb_field('prerendered_key_only', XMLDB_TYPE_CHAR, '40', null, null, null, null, 'prerendered_with_key');

        // Conditionally launch add field prerendered_key_only
        if (!$dbman->field_exists($table, $field)) {
            $dbman->add_field($table, $field);
        }

        // papercopy savepoint reached
        upgrade_plugin_savepoint(true, 2012082904, 'quiz', 'papercopy');
    }


    // Upgrade to 10-15-12 V1
    if ($oldversion < 2012101501) {

        // Define field id to be added to quiz_papercopy_batches
        $table = new xmldb_table('quiz_papercopy_batches');
        $field = new xmldb_field('entrymethod', XMLDB_TYPE_INTEGER, '3', null, XMLDB_NOTNULL, null, 0, null);

        // Conditionally launch add field id
        if (!$dbman->field_exists($table, $field)) {
            $dbman->add_field($table, $field);
        }

        // papercopy savepoint reached
        upgrade_plugin_savepoint(true, 2012101501, 'quiz', 'papercopy');
    }

}
